language: node_js
node_js:
  - "14"
cache:
  # Caches $HOME/.npm when npm ci is default script command
  # Caches node_modules in all other cases
  yarn: true
  directories:
    # we also need to cache folder with Cypress binary
    - ~/.cache
script:
  - cd example && yarn
  - cd .. && yarn ci