name: React-contexify CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
            node-version: '14.x'
      - name: Install example dependencies
        run: cd example && yarn
      - name: Install dependencies & build
        run: yarn 
      - name: Lint
        run: yarn lint
      - name: Run cypress 
        uses: cypress-io/github-action@v2
        with:
            browser: chrome
            start: yarn start:example
            wait-on: 'http://localhost:1234'
      - uses: actions/upload-artifact@v1
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      
      - uses: actions/upload-artifact@v1
        if: always()
        with:
          name: cypress-videos
          path: cypress/videos
      
      
